name: Build and deploy Node.js app to Azure Web App - ProyectoGlory

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
      
      # - name: Create ZIP archive
      #   run: zip -r node-app.zip .

      - name: Create ZIP archive
        # run: Compress-Archive -Path . -DestinationPath node-app.zip
        run: zip -r node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # - name: Unzip artifact for deployment
      #   run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61687A6372BE47F9980C536F5B36ED20 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C8ABE48494446B8B6F92EC019349516 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_78A656CF1C164D5B8FC7F2C99DF3D9B6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ProyectoGlory'
          slot-name: 'Production'
          package: .
          